language: objective-c

osx_image: xcode8.3

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.sbt
  - platform
  - apps

install:
  - mkdir -p bin
  - wget -qO bin/prelude.sh https://raw.githubusercontent.com/sireum/v3/master/bin/prelude.sh
  - chmod +x bin/prelude.sh
  - bin/prelude.sh
  - export PATH=$TRAVIS_BUILD_DIR/platform/java/bin:$TRAVIS_BUILD_DIR/platform/scala/bin:$TRAVIS_BUILD_DIR/platform/sbt/bin:$TRAVIS_BUILD_DIR/platform/node/bin:$TRAVIS_BUILD_DIR/apps/z3/bin:$PATH

script:
  - sbt clean test:compile test