version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
  JAVA_OPTS: '-Xmx2G'
  JAVA_HOME: 'C:\Program Files\Java\jdk10'
  PATH: 'C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%JAVA_HOME%\bin;%PATH%'

build_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./test.sh"
